GET http://127.0.0.1:3000/api/user/state
Cookie: next-auth.session-token=eyJhbGciOiJkaXIiLCJlbmMiOiJBMjU2Q0JDLUhTNTEyIiwia2lkIjoicTBRSGNxaklnbkdEbjVhSEN0ZWVpRlFlT0EwTGFTcUVNUTBzdUZISmJlOU1pVEhlM2RUUWs2bzBBNjFZeFZKNWJzN0Z6WUdnWjZjSV9xNVZlSkN2VXcifQ..IgbDfGKQyoEz7J1rzGZTFw.uWqnaN2gK3EVShE7FdwHsxvhDk6ODmEhDs2_CgUpu0zCkmWz0M7lXpiCrrvL7UayvQeME1b473uqAdFrQn9LwCBaIxVH_5JnlEvQ1d0SCAdixemGSbSHkII6EYZ0VTl-J_9DNgcbNbNLtxNbZ4hR1kyc4eOlluREDvv6tmBb8ItnLzuyAReBCvsp2NW6hD44q6O1NXq7pBhxtnOa0loQjqmLLIhJBsKZV6D7PGOfUpOMucJJ3BQD2kPaJ5HXxh3HVvgQVDI2Vrib4l-_KDP5GDqQs6Is8okZiqURmLXMsFMv1tAIA4C7B6f1eNCjpOIS4I9xnpncd2FeXkFCQv0zyAxrwEJ13T6Foza0B5vOrrNeKOevg8z6bBN8pWCCQoEOwJHnEmdGEZAtIzcKHjv9T3hQcf4mnLPuH4fNKEgaDrDLCqd0yHnNdZtbQfBgHD9sHEWYveKIR3Pjl4VvwaDNAuseICqhFakw5IgTcUsH2wFWmJy9YqMb7-FnX9p8z4mRvv0MTYjddgHZP52HhfDf4qbbYbf--Re-OaNZ1ncbzgsdWZo8icWR0bOmBwnS_Mv8atnlRrobmey_ce_Fb02KfQ.tOtdRguMkU9fK0EtMGySGWmBE0ArvKPsUduqrd7avPw; react-resizable-panels:pc-layout=[12,30,58]; react-resizable-panels:m-layout=[12,88]

