### Mail Scroll
POST http://127.0.0.1:3000/api/mail/scroll
Content-Type: application/json

{}


### Mail History Scroll
POST http://127.0.0.1:3000/api/mail/history/scroll
Content-Type: application/json

{
  "owner": "cc@hocg.in"
}


### Query Mail Accounts
GET http://127.0.0.1:3000/api/mail/accounts
Content-Type: application/json



### Send Mail
POST http://127.0.0.1:3000/api/mail/send
Content-Type: application/json

{}
