### Mail Scroll
POST http://127.0.0.1:3000/api/mail/scroll
Content-Type: application/json

{}


### Mail History Scroll
POST http://127.0.0.1:3000/api/mail/history/scroll
Content-Type: application/json

{
  "owner": "cc@hocg.in"
}


### Query Mail Accounts
GET http://127.0.0.1:3000/api/user/account
Content-Type: application/json



### Send Mail
POST {{host}}/api/mail/send
Content-Type: application/json
X-Requested-With: XMLHttpRequest

{
  "to": [
    {
      "address": "hocgin@gmail.com",
      "name": "夏不来"
    }
  ],
  "from": {
    "address": "cc@hocg.in",
    "name": ""
  },
  "subject": "Reply to hocgin@gmail.com",
  "html": "testt"
}



### Query Mail Detail
GET {{host}}/api/mail/1
Content-Type: application/json
